import {InfoHint} from '../../common/InfoHint';
import {TemplateEditor} from './TemplateEditor';
import { EnvironmentBadge } from "../sessions/EnvironmentBadge";
import {useEffect,useRef,useState} from 'react';
import {Button,Checkbox,Dialog,DialogSurface,DialogBody,DialogTitle,DialogContent,DialogActions,Field,Input,Spinner,ProgressBar,Textarea} from '@fluentui/react-components';
import {AddRegular,DeleteRegular,SaveRegular,ArrowDownloadRegular,ArrowUploadRegular,PlayRegular,EditRegular,ArrowSyncRegular,DismissRegular,SparkleRegular} from '@fluentui/react-icons';
import {open,save} from '@tauri-apps/plugin-dialog';
import {api} from '../../ipc';
import {mongo} from '../mongo/api';
import {useTabStore,type GenerationTab} from '../../stores/useTabStore';
import {useSessionStore} from '../../stores/useSessionStore';
import {useWorkspace} from '../../stores/useWorkspace';
import {usePendingEdit} from '../../stores/useEditGuard';
import {cancelTask,errorText,isTaskActive,useTaskStore} from '../../stores/useTaskStore';
import {useNotify} from '../../app/toast';
import {generationApi as gen,RULES,directAiFields,prepareDirectAiPlan,assertSafeNumbers,newRule,defaultRules,validateTemplate,type Target,type Plan,type Description,type Preview,type Provider,type FieldRule,type WriteReport,type Template,type Usage} from './model';
import {loadTemplates,storeTemplate,deleteTemplate,useGenerationTemplates} from './templates';
import {AiResponseViewer} from './AiResponseViewer';
import {GenerationMonitor,useGenerationTrace} from './GenerationMonitor';
import {progressDisplay} from '../../app/taskProgress';
import './generation.css';
const blank=(t:Target):Plan=>({version:1,target:t,count:100,seed:'1',fields:[],parameters:{prefix:crypto.randomUUID().slice(0,8)},ai:null});
const compact=(v:unknown)=>v===undefined?'（省略）':v===null?'NULL':typeof v==='string'?v:JSON.stringify(v);
export function GenerationLauncher(){const notify=useNotify();useEffect(()=>{const show=(event:Event)=>{const state=useSessionStore.getState(),tabs=useTabStore.getState(),tab=tabs.tabs.find(t=>t.id===tabs.activeId);const context=(event as CustomEvent<Partial<Target>>).detail;const sessionId=context?.sessionId??state.activeSessionId;const session=state.sessions.find(s=>s.id===sessionId);if(!session){notify.error('请先选择一个会话');return;}const t:Target={sessionId:session.id,database:context?.database??(tab?.sessionId===session.id?tab.database:'')??'',schema:context?.schema??(tab?.kind==='table'?tab.schema??null:null),object:context?.object??(tab?.kind==='table'?tab.table:tab?.kind==='mongo'?tab.collection:session.engine==='redis'?'keys':''),redisKind:session.engine==='redis'?'string':null,ttlSeconds:null};tabs.openGeneration(t);window.dispatchEvent(new Event('dw:show-workspace'));};window.addEventListener('dw:generation',show);return()=>window.removeEventListener('dw:generation',show);},[notify]);return null;}
export function GenerationWorkspace({tab}:{tab:GenerationTab}){
 const session=useSessionStore(s=>s.sessions.find(s=>s.id===tab.sessionId)),connected=useSessionStore(s=>!!s.statuses[tab.sessionId]);
 const templates=useGenerationTemplates(s=>s.items);
 const notify=useNotify(),monitor=useGenerationTrace();
 const [monitorOpen,setMonitorOpen]=useState(false),[failure,setFailure]=useState(''),[responseOpen,setResponseOpen]=useState(false);
 const [plan,setPlan]=useState<Plan>(()=>useWorkspace.getState().generationPlans[tab.id]??blank(tab.target));
 const [desc,setDesc]=useState<Description|null>(null),[preview,setPreview]=useState<Preview|null>(null),[report,setReport]=useState<WriteReport|null>(null),[step,setStep]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[note,setNote]=useState('');
 const [dbs,setDbs]=useState<string[]>([]),[objects,setObjects]=useState<{name:string;schema:string|null}[]>([]),[providers,setProviders]=useState<Provider[]>([]),[selected,setSelected]=useState<string[]>([]),[bulk,setBulk]=useState('text'),[templateId,setTemplateId]=useState(''),[templateName,setTemplateName]=useState(''),[modal,setModal]=useState<'write'|'save'|'delete'|'suggest'|'cell'|null>(null),[cell,setCell]=useState(''),[edit,setEdit]=useState<number|null>(null),[suggestion,setSuggestion]=useState<{fields:FieldRule[];usage:Usage}|null>(null),[aiPrompt,setAiPrompt]=useState(plan.ai?.prompt??'');
 const [parameters,setParameters]=useState(()=>JSON.stringify(plan.parameters,null,2));
 const generationSerial=useRef(0);
 const busyRef=useRef(false),artifact=useRef<string|null>(null),mounted=useRef(true);
 const tasks=useTaskStore(s=>s.tasks),activeTasks=tasks.filter(t=>isTaskActive(t)&&t.tabId===tab.id);
 const dropPreview=()=>{if(artifact.current){void gen.release(artifact.current).catch(()=>{});artifact.current=null;}setPreview(null);setReport(null);};
 const change=(update:Partial<Plan>)=>{dropPreview();setPlan(p=>({...p,...update}));};
 const run=async(action:()=>Promise<void>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');setNote('');try{await action();}catch(e){if(mounted.current){const message=errorText(e);setError(message);setFailure(message);setModal(null);notify.error(e,'数据生成操作失败');}}finally{busyRef.current=false;if(mounted.current)setBusy(false);}};
 const reloadProviders=async()=>{const items=await gen.providers();setProviders(items);const preferred=items.find(p=>p.isDefault)??(items.length===1?items[0]:undefined);if(preferred)setPlan(p=>p.ai?p:{...p,ai:{providerId:preferred.id,model:preferred.model,prompt:aiPrompt}});};
 useEffect(()=>{mounted.current=true;void Promise.all([loadTemplates(),reloadProviders()]).catch(e=>setError(errorText(e)));return()=>{mounted.current=false;if(artifact.current)void gen.release(artifact.current).catch(()=>{});};},[]);
 useEffect(()=>{useWorkspace.setState(s=>({generationPlans:{...s.generationPlans,[tab.id]:plan}}));useTabStore.setState(s=>({tabs:s.tabs.map(t=>t.id===tab.id&&t.kind==="generation"?{...t,database:plan.target.database,title:'数据生成'+(plan.target.object?' · '+plan.target.object:''),target:plan.target}:t)}));},[plan,tab.id]);
 usePendingEdit({tabId:tab.id,sessionId:tab.sessionId,label:'正在生成或写入数据',busy:()=>busyRef.current,save:async()=>{},discard:()=>{}},busy);
 const describe=async()=>{const d=await gen.describe(plan.target);setDesc(d);if(!plan.fields.length){change({fields:defaultRules(d,plan.target.redisKind)});}setStep(1);setSelected([]);};
 const loadTargets=async()=>{if(!session)return;if(session.engine==='redis'){setDbs((await api.redisDatabases(session.id)).map(v=>'db'+v.index));return;}const list=await api.listDatabases(session.id);setDbs(list.map(d=>d.name));if(plan.target.database){if(session.engine==='mongodb')setObjects((await mongo.collections(session.id,plan.target.database)).map(name=>({name,schema:null})));else setObjects((await api.listTables(session.id,plan.target.database)).filter(t=>t.kind==='table').map(t=>({name:t.name,schema:t.schema??null})));}};
 useEffect(()=>{if(!connected)return;void run(loadTargets);},[connected,plan.target.database]);
 const retarget=(patch:Partial<Target>)=>{setDesc(null);if(patch.database!==undefined)setObjects([]);change({target:{...plan.target,...patch},fields:[]});setStep(0);};
 const fieldUpdate=(index:number,value:FieldRule)=>change({fields:plan.fields.map((f,i)=>i===index?value:f)});
 const makeTemplate=(name:string,id?:string):Template=>({version:1,id:id??crypto.randomUUID(),name,engine:session!.engine,fields:plan.fields,count:plan.count,seed:plan.seed,parameters:plan.parameters,redisKind:plan.target.redisKind,ttlSeconds:plan.target.ttlSeconds});
 const apply=(t:Template)=>{if(t.engine!==session?.engine)throw Error('模板数据库类型不匹配');change({fields:structuredClone(t.fields),count:t.count,seed:t.seed,parameters:{...t.parameters},target:{...plan.target,redisKind:t.redisKind,ttlSeconds:t.ttlSeconds}});setParameters(JSON.stringify(t.parameters,null,2));setSelected([]);setNote('模板已应用，请检查字段映射和必填规则；写入前会重新校验');};
 const provider=providers.find(p=>p.id===plan.ai?.providerId);
 const chooseProvider=(id:string)=>{const p=providers.find(p=>p.id===id);change({ai:p?{providerId:p.id,model:p.model,prompt:aiPrompt}:null});};
 const generate=async(direct=false)=>{const params:unknown=JSON.parse(parameters);if(!params||typeof params!=='object'||Array.isArray(params)||Object.values(params).some(v=>typeof v!=='string'))throw Error('参数必须是名称到字符串的对象');const configured:Plan={...plan,parameters:params as Record<string,string>,ai:plan.ai?{...plan.ai,prompt:aiPrompt}:null};const next=direct?prepareDirectAiPlan(configured,desc!):configured;dropPreview();setPlan(next);const serial=++generationSerial.current;monitor.start(next.count);setMonitorOpen(true);try{const p=await gen.generate(next,event=>{if(serial===generationSerial.current)monitor.receive(event);});if(!mounted.current){await gen.release(p.id);return;}artifact.current=p.id;setPreview(p);setStep(2);if(!monitor.current.current?.rows.length)p.rows.forEach((row,i)=>monitor.receive({kind:'validated',number:i+1,row}));monitor.receive({kind:'progress',count:p.count,usage:p.usage});monitor.finish('success');notify.success('生成成功',`已生成并校验 ${p.count} 条，尚未写入数据库`);}catch(e){if(mounted.current){const message=errorText(e);monitor.finish((e as {code?:string})?.code==='E_CANCELLED'?'cancelled':'error',message);setError(message);setMonitorOpen(true);notify.error(e,'数据生成失败');}}};
 const exportBatch=async(format:string)=>{const path=await save({defaultPath:`generated.${format}`,filters:[{name:format.toUpperCase(),extensions:[format]}]});if(path&&preview){await gen.export(preview.id,path,format,tab.sessionId);setNote('已导出当前预览的完整批次');}};
 if(!session)return <div className="dw-generation">会话已删除。</div>;
 const directFields=desc?directAiFields(plan.fields,desc).filter(f=>f.kind==='ai'):[];
 const hasAiFields=plan.fields.some(f=>f.kind==='ai');
 const generationProgress=monitor.trace?progressDisplay(monitor.trace.count,monitor.trace.total):null;
 const names=preview?[...new Set(preview.rows.flatMap(r=>Object.keys(r)))]:[];
 return <div className="dw-generation" style={{containerType:'inline-size'}}><div className="gen-toolbar"><h2>数据生成</h2><span className="gen-note">{session.name} · {session.engine} {session.readOnly?'· 只读（可预览/导出）':''}</span><span style={{flex:1}}/>{busy&&<Button icon={<DismissRegular/>} disabled={!activeTasks.length} onClick={()=>void Promise.all(activeTasks.map(t=>cancelTask(t.id))).catch(e=>setError(errorText(e)))}>停止当前任务</Button>}</div>
 <nav className="gen-steps" aria-label="生成步骤">{['1 目标','2 规则与模板','3 预览与写入','4 执行结果'].map((title,i)=><Button key={i} appearance={step===i?'primary':'subtle'} disabled={busy||(i===1&&!desc)||(i===2&&!preview)||(i===3&&!report)} onClick={()=>setStep(i)}>{title}</Button>)}</nav>
 {busy&&<Spinner size="tiny" label={activeTasks[0]?.progress?.message??'处理中…'}/>} {monitor.trace&&<div className="gen-toolbar gen-process-strip"><strong>{monitor.trace.status==='running'?'正在生成':monitor.trace.status==='success'?'生成成功':monitor.trace.status==='cancelled'?'生成已停止':'生成失败'}</strong><span>已校验 {monitor.trace.count} / {monitor.trace.total}</span><div className="gen-strip-progress"><ProgressBar aria-label="数据生成校验进度" value={generationProgress?.value} color={monitor.trace.status==='error'?'error':monitor.trace.status==='success'?'success':'brand'}/><strong>{generationProgress?.percent??0}%</strong></div><Button size="small" onClick={()=>setMonitorOpen(true)}>查看生成过程</Button></div>}{error&&<div role="alert" className="gen-result-banner is-error gen-sticky-alert"><strong>操作未完成</strong><p className="gen-error">{error}</p><div className="gen-toolbar"><Button size="small" onClick={()=>setFailure(error)}>查看原因</Button>{monitor.trace&&<Button size="small" onClick={()=>setResponseOpen(true)}>查看 AI 响应</Button>}<Button size="small" onClick={()=>setError('')}>收起提醒</Button></div></div>}{note&&<div role="status" className="gen-result-banner is-success">{note}</div>}
 {step===0&&<div className="gen-card"><h3>选择生成目标</h3><p className="gen-note">从已连接会话中读取结构。生成和预览不会写入数据库。</p><fieldset disabled={busy||!connected} className="gen-form"><div className="gen-two"><Field label="数据库"><select className="dw-native-select" value={plan.target.database} onChange={e=>retarget({database:e.target.value,object:session.engine==='redis'?'keys':'',schema:null})}><option value="">请选择</option>{[...new Set([...dbs,...(plan.target.database?[plan.target.database]:[])])].map(d=><option key={d}>{d}</option>)}</select></Field>
 {session.engine==='redis'?<Field label="键类型"><select className="dw-native-select" value={plan.target.redisKind??'string'} onChange={e=>retarget({redisKind:e.target.value,object:'keys'})}><option value="string">String</option><option value="hash">Hash</option></select></Field>:<Field label={session.engine==='mongodb'?'集合':'数据表'}><select className="dw-native-select" value={JSON.stringify([plan.target.schema,plan.target.object])} onChange={e=>{const[schema,object]=JSON.parse(e.target.value);retarget({schema,object});}}><option value={JSON.stringify([null,''])}>请选择</option>{(objects.some(o=>o.name===plan.target.object&&o.schema===plan.target.schema)||!plan.target.object?objects:[{name:plan.target.object,schema:plan.target.schema},...objects]).map(o=><option key={JSON.stringify(o)} value={JSON.stringify([o.schema,o.name])}>{o.schema?o.schema+'.':''}{o.name}</option>)}</select></Field>}
 {session.engine==='redis'&&<Field label="TTL 秒（留空永久）"><Input type="number" min={1} value={plan.target.ttlSeconds===null?'':String(plan.target.ttlSeconds)} onChange={(_,d)=>retarget({ttlSeconds:d.value?Number(d.value):null})}/></Field>}</div><div className="gen-toolbar"><Button icon={<ArrowSyncRegular/>} onClick={()=>void run(loadTargets)}>刷新目标列表</Button><Button appearance="primary" disabled={!plan.target.database||!plan.target.object} onClick={()=>void run(describe)}>读取结构，配置规则</Button></div></fieldset>{!connected&&<p>会话未连接，规则已保留。</p>}</div>}
 {step===1&&desc&&<><div className="gen-card"><div className="gen-toolbar"><h3>批量模板</h3><select aria-label="已保存模板" className="dw-native-select" value={templateId} disabled={busy} onChange={e=>setTemplateId(e.target.value)}><option value="">选择模板</option>{templates.filter(t=>t.engine===session.engine).map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select><Button disabled={busy||!templateId} onClick={()=>void run(async()=>apply(templates.find(t=>t.id===templateId)!))}>应用</Button><Button disabled={busy||!plan.fields.length} icon={<SaveRegular/>} onClick={()=>{setTemplateName(templates.find(t=>t.id===templateId)?.name??'');setModal('save');}}>保存 / 另存</Button><Button disabled={busy||!templateId} onClick={()=>void run(async()=>{const t=templates.find(t=>t.id===templateId)!;const copy={...t,id:crypto.randomUUID(),name:t.name+' 副本'};await storeTemplate(copy);setTemplateId(copy.id);})}>复制</Button><Button disabled={busy||!templateId} icon={<DeleteRegular/>} title="删除模板" aria-label="删除模板" onClick={()=>setModal('delete')}/><Button disabled={busy} icon={<ArrowUploadRegular/>} onClick={()=>void run(async()=>{const path=await open({multiple:false,filters:[{name:'生成模板',extensions:['json']}]});if(typeof path==='string'){const t=validateTemplate(JSON.parse(await gen.readTemplate(path)));if(t.engine!==session.engine)throw Error('导入模板数据库类型不匹配');await storeTemplate(t);setTemplateId(t.id);setNote('模板已导入，点击应用使用');}})}>导入</Button><Button disabled={busy||!plan.fields.length} icon={<ArrowDownloadRegular/>} onClick={()=>void run(async()=>{const path=await save({defaultPath:'generation-template.json',filters:[{name:'生成模板',extensions:['json']}]});if(path)await gen.writeTemplate(path,JSON.stringify(makeTemplate(templateName||'生成模板'),null,2));})}>导出</Button></div><div className="gen-three"><Field label="生成数量（1–100000；AI 字段最多 2000）"><Input disabled={busy} type="number" min={1} max={100000} value={String(plan.count)} onChange={(_,d)=>change({count:Number(d.value)})}/></Field><Field label="随机种子（随机 UUID、批次号和当前时间除外）"><Input disabled={busy} value={plan.seed} maxLength={100} onChange={(_,d)=>change({seed:d.value})}/></Field><Field label="当前目标"><Input readOnly value={`${plan.target.database}.${plan.target.schema?plan.target.schema+'.':''}${plan.target.object}`}/></Field></div></div>
 <div className="gen-card"><div className="gen-toolbar"><h3>AI 直接生成数据</h3><Button size="small" disabled={busy} onClick={()=>void run(reloadProviders)}>刷新服务列表</Button><Button size="small" onClick={()=>window.dispatchEvent(new CustomEvent('dw:settings',{detail:{category:'ai'}}))}>前往首选项 AI 服务</Button></div><div className="gen-two"><Field label="AI 服务"><select className="dw-native-select" disabled={busy} value={plan.ai?.providerId??''} onChange={e=>chooseProvider(e.target.value)}><option value="">请选择 AI 服务</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}{p.isDefault?' · 默认':''}</option>)}</select></Field><Field label="本次模型"><Input disabled={busy||!plan.ai} value={plan.ai?.model??''} placeholder={provider?.model??'先选择 AI 服务'} onChange={(_,d)=>change({ai:plan.ai?{...plan.ai,model:d.value}:null})}/></Field></div><Checkbox disabled={busy||!plan.ai} checked={plan.ai?.stream!==false} label="流式接收并实时显示（不支持流式的服务可关闭）" onChange={(_,d)=>change({ai:plan.ai?{...plan.ai,stream:!!d.checked}:null})}/><Textarea disabled={busy} aria-label="AI 生成要求" placeholder="例如：生成 100 条电商商品，名称自然，价格 10–500 元，分类从指定候选值中选择" value={aiPrompt} onChange={(_,d)=>{setAiPrompt(d.value);change({ai:plan.ai?{...plan.ai,prompt:d.value}:null});}} resize="vertical"/><InfoHint label="AI 字段生成说明">直接让模型生成业务内容，无需逐个修改字段规则。数量以上方设置为准；序列、UUID、ObjectId、计算字段、数据库默认值和 Redis 键名保留原规则。</InfoHint><p className="gen-note">AI 生成字段（{directFields.length}）：{directFields.map(f=>f.name).join("、")||"暂无，请调整字段规则"}</p><div className="gen-toolbar"><Button appearance="primary" icon={<SparkleRegular/>} disabled={busy||!connected} onClick={()=>void run(()=>generate(true))}>AI 直接生成数据</Button><Button icon={<SparkleRegular/>} disabled={busy||!provider||!aiPrompt.trim()} onClick={()=>void run(async()=>{const result=await gen.suggest(plan.target,{...plan.ai!,prompt:aiPrompt});setSuggestion(result);setModal('suggest');})}>仅建议生成规则…</Button><InfoHint label="生成与规则建议说明">直接生成会请求模型、校验内容并打开预览，不会写入数据库。规则建议仅用于配置本地批量生成。</InfoHint></div><details><summary>查看将发送的上下文与范围</summary><p className="gen-note">发送到 {provider?.baseUrl??'所选服务'}：你的要求、字段名称/类型/注释及规则。AI 内容字段还会发送当前批次的本地生成值（每批最多 10 条）以保持关联；不会自动发送已有数据库记录。模板不包含密钥。直接生成按钮会将上述业务字段切换为“AI 生成内容”；也可以在字段规则中单独指定 AI 字段。</p><pre className="gen-code">{JSON.stringify({targetFields:desc.fields,instruction:aiPrompt,directAiFields:directFields,currentAiFields:plan.fields.filter(f=>f.kind==='ai')},null,2)}</pre></details></div>
 <div className="gen-card"><div className="gen-toolbar"><h3>字段规则</h3><span className="gen-note">已选 {selected.length} 项</span><select aria-label="批量规则" className="dw-native-select" value={bulk} disabled={busy} onChange={e=>setBulk(e.target.value)}>{Object.entries(RULES).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select><Button disabled={busy||!selected.length} onClick={()=>change({fields:plan.fields.map(f=>selected.includes(f.name)?newRule(f.name,bulk):f)})}>批量应用规则</Button>{session.engine==='mongodb'&&<Button icon={<AddRegular/>} disabled={busy} onClick={()=>{let n=1;while(plan.fields.some(f=>f.name==='field'+n))n++;change({fields:[...plan.fields,newRule('field'+n,'text')]});}}>添加字段</Button>}<Button disabled={busy} onClick={()=>{change({fields:defaultRules(desc,plan.target.redisKind)});setSelected([]);}}>重置建议规则</Button></div>
 <div className="gen-table-scroll"><table className="gen-table"><thead><tr><th><Checkbox aria-label="全选字段" disabled={busy} checked={selected.length>0&&selected.length===plan.fields.filter(f=>!desc.fields.find(d=>d.name===f.name)?.generated).length} onChange={(_,d)=>setSelected(d.checked?plan.fields.filter(f=>!desc.fields.find(d=>d.name===f.name)?.generated).map(f=>f.name):[])}/></th><th>字段 / 类型</th><th>生成规则</th><th>规则参数</th><th>空值 %</th><th>批次内唯一</th>{session.engine==='mongodb'&&<th/>}</tr></thead><tbody>{plan.fields.map((f,i)=>{const meta=desc.fields.find(d=>d.name===f.name);return<tr key={i}><td><Checkbox aria-label={'选择 '+f.name} disabled={busy||meta?.generated} checked={selected.includes(f.name)} onChange={(_,d)=>setSelected(s=>d.checked?[...s,f.name]:s.filter(n=>n!==f.name))}/></td><td>{session.engine==='mongodb'?<Input aria-label="字段名称" disabled={busy} value={f.name} style={{width:160}} onChange={(_,d)=>fieldUpdate(i,{...f,name:d.value})}/>:<strong>{f.name}</strong>}<small className="gen-note" style={{display:'block'}}>{meta?.rawType??'自定义字段'}{meta?.generated?' · 数据库生成':''}{meta&&!meta.nullable?' · 非空':''}</small></td><td><select className="dw-native-select" aria-label={f.name+' 的规则'} disabled={busy||meta?.generated} value={f.kind} onChange={e=>fieldUpdate(i,newRule(f.name,e.target.value))}>{Object.entries(RULES).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></td><td><Button size="small" icon={<EditRegular/>} disabled={busy||!Object.keys(f.args).length} title={JSON.stringify(f.args)} onClick={()=>setEdit(i)}><span style={{maxWidth:160,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{Object.keys(f.args).length?JSON.stringify(f.args):'无需参数'}</span></Button></td><td><input aria-label={f.name+' 空值比例'} type="number" min={0} max={100} className="dw-native-select" disabled={busy||meta?.nullable===false||['omit','ai','compute','null'].includes(f.kind)} value={f.nullPercent} onChange={e=>fieldUpdate(i,{...f,nullPercent:Number(e.target.value)})}/></td><td><Checkbox aria-label={f.name+' 批次内唯一'} disabled={busy||f.kind==='omit'} checked={f.unique} onChange={(_,d)=>fieldUpdate(i,{...f,unique:!!d.checked})}/></td>{session.engine==='mongodb'&&<td><Button icon={<DeleteRegular/>} size="small" disabled={busy} aria-label={'删除规则 '+f.name} onClick={()=>{change({fields:plan.fields.filter((_,j)=>i!==j)});setSelected([]);}}/></td>}</tr>;})}</tbody></table></div><InfoHint label="字段类型与校验说明">序列 / 大整数 / 小数按字符串保存精度，SQL 适配器按列类型绑定；MongoDB 中整数规则保存为 BSON Int64，小数为 Decimal128，日期为 UTC BSON Date；固定值 / 候选值也支持 Extended JSON。AI 返回的值也会校验。唯一检查不会自动“修复”或丢弃重复行。</InfoHint>
 <details><summary>方案参数（文本模板可引用）</summary><textarea className="gen-json" disabled={busy} value={parameters} onChange={e=>{setParameters(e.target.value);dropPreview();}} onBlur={()=>{try{const v=JSON.parse(parameters);if(v&&typeof v==='object'&&!Array.isArray(v)&&Object.values(v).every(x=>typeof x==='string'))change({parameters:v});}catch{/* 生成时显示校验错误 */}}} aria-label="模板参数 JSON"/></details></div>
 {desc.warnings.map((w,i)=><p className="gen-note" key={i}>{w}</p>)}<div className="gen-toolbar"><Button appearance="primary" icon={<PlayRegular/>} disabled={busy||!connected||!plan.fields.length} onClick={()=>void run(()=>generate())}>{hasAiFields?"按当前规则生成（含 AI）":"按本地规则生成"}</Button><span className="gen-note">{hasAiFields?"含 AI 字段":"本地生成"} · 仅预览，未写入</span></div></>}
 {step===2&&preview&&<><div className="gen-summary"><span>总计 <strong>{preview.count}</strong> 条</span><span>{(preview.bytes/1024).toFixed(1)} KiB</span><span>{preview.usage.requests?"来源：AI + 本地规则":"来源：本地规则（未调用 AI）"} · AI 请求 {preview.usage.requests} 次 · tokens {preview.usage.inputTokens??'未报告'} / {preview.usage.outputTokens??'未报告'}</span><span>{preview.status==='ready'?'待写入':'该批次已提交过，仅可导出'}</span></div><InfoHint label="预览说明">以下为冻结批次，确认后写入同一份数据，不会再次生成。单元格点击可查看完整内容；JSON 数字与字符串保留各自类型。</InfoHint><div className="gen-table-scroll"><table className="gen-table"><thead><tr><th>#</th>{names.map(n=><th key={n}>{n}</th>)}</tr></thead><tbody>{preview.rows.map((r,i)=><tr key={i}><td>{preview.offset+i+1}</td>{names.map(n=><td key={n}><Button appearance="transparent" size="small" title="查看完整生成值" onClick={()=>{setCell(JSON.stringify(r[n],null,2)??'（省略）');setModal('cell');}}><pre>{compact(r[n])}</pre></Button></td>)}</tr>)}</tbody></table></div><div className="gen-toolbar"><Button disabled={busy||preview.offset===0} onClick={()=>void run(async()=>setPreview(await gen.preview(preview.id,Math.max(0,preview.offset-50))))}>上一页</Button><span>{preview.offset+1}–{preview.offset+preview.rows.length} / {preview.count}</span><Button disabled={busy||preview.offset+50>=preview.count} onClick={()=>void run(async()=>setPreview(await gen.preview(preview.id,preview.offset+50)))}>下一页</Button><span style={{flex:1}}/>{['json','jsonl',...(session.engine==='mongodb'?[]:['csv'])].map(f=><Button icon={<ArrowDownloadRegular/>} key={f} disabled={busy} onClick={()=>void run(()=>exportBatch(f))}>导出 {f.toUpperCase()}</Button>)}</div><div className="gen-toolbar"><Button appearance="primary" icon={<SaveRegular/>} disabled={busy||!connected||session.readOnly||!desc?.writeSupported||preview.status!=='ready'} onClick={()=>setModal('write')}>确认写入…</Button><Button disabled={busy} onClick={()=>setStep(1)}>返回修改规则</Button></div>{preview.warnings.map((w,i)=><p className="gen-note" key={i}>{w}</p>)}</>}
 {step===3&&report&&<div className="gen-card"><h3>{report.cancelled?'任务已停止':report.error?'任务中止，请核对结果':'生成数据已写入'}</h3><div className="gen-summary"><span>已提交 <strong>{report.inserted}</strong></span><span>明确失败 {report.failed}</span><span>待核对 {report.uncertain}</span><span>未尝试 {report.unattempted}</span></div>{report.error&&<p className="gen-error">{report.error}</p>}<p className="gen-note">已提交数据保留；再次生成前请核对数据库。</p><div className="gen-toolbar"><Button onClick={()=>setStep(2)}>查看 / 导出本批次</Button><Button onClick={()=>{dropPreview();setStep(1);}}>配置新批次</Button></div></div>}
 <AiResponseViewer trace={monitor.trace} open={responseOpen} onClose={()=>setResponseOpen(false)} onProcess={()=>{setResponseOpen(false);setMonitorOpen(true);}}/>
 <GenerationMonitor onResponses={()=>{setMonitorOpen(false);setResponseOpen(true);}} trace={monitor.trace} open={monitorOpen} onClose={()=>setMonitorOpen(false)} onPreview={()=>{setMonitorOpen(false);setStep(2);}} cancelEnabled={!!activeTasks.length} onCancel={()=>void Promise.all(activeTasks.map(t=>cancelTask(t.id))).catch(e=>notify.error(e))}/>
 <Dialog open={!!failure} onOpenChange={(_,d)=>{if(!d.open)setFailure('');}}><DialogSurface style={{maxWidth:640}}><DialogBody><DialogTitle>操作未完成</DialogTitle><DialogContent><div className="gen-result-banner is-error" role="alert"><strong>失败原因</strong><p className="gen-error">{failure}</p></div></DialogContent><DialogActions>{monitor.trace&&<Button onClick={()=>{setFailure('');setResponseOpen(true);}}>查看 AI 响应</Button>}<Button appearance="primary" onClick={()=>setFailure('')}>知道了，返回修改</Button></DialogActions></DialogBody></DialogSurface></Dialog>
 {edit!==null&&plan.fields[edit]&&<RuleDialog field={plan.fields[edit]} onClose={()=>setEdit(null)} onSave={f=>{fieldUpdate(edit,f);setEdit(null);}}/>}
 <Dialog open={modal!==null} onOpenChange={(_,d)=>{if(!d.open&&!busy)setModal(null);}}><DialogSurface style={{maxWidth:760,width:'90vw'}}><DialogBody><DialogTitle>{{write:'确认写入生成数据',save:'保存生成模板',delete:'删除模板',suggest:'检查 AI 规则建议',cell:'生成值详情'}[modal??'cell']}</DialogTitle><DialogContent style={{maxHeight:'60vh',overflow:'auto'}}>
 {modal==='write'&&<><p>将向 <EnvironmentBadge sessionId={session.id}/><strong>{session.name} / {plan.target.database} / {plan.target.object}</strong> 新增 <strong>{preview?.count}</strong> 条数据。</p><p>主机：{session.host??session.filePath} · 用户：{session.username??'本地'} · {session.engine}</p><p>仅插入，不覆盖已有记录。SQL 每 100 条一个事务；MongoDB / Redis 逐条提交。约束冲突会停止，已提交部分保留。执行中可取消后续批次。</p></>}
 {modal==='save'&&<><Input aria-label="模板名称" value={templateName} maxLength={80} onChange={(_,d)=>setTemplateName(d.value)} placeholder="例如：商品基础数据"/><InfoHint label="模板保存范围">保存字段规则、数量、种子与参数；不保存连接地址、账号或 AI 密钥。可跨同类数据库复用，应用后仍需校验字段。</InfoHint></>}
 {modal==='delete'&&<p>删除模板「{templates.find(t=>t.id===templateId)?.name}」？当前页的规则仍保留。</p>}
 {modal==='suggest'&&suggestion&&<><p>建议尚未应用。确认后替换当前字段规则，已有预览将失效。</p><p className="gen-note">输入 {suggestion.usage.inputTokens??'未报告'} / 输出 {suggestion.usage.outputTokens??'未报告'} tokens</p><pre className="gen-code">{JSON.stringify(suggestion.fields,null,2)}</pre></>}
 {modal==='cell'&&<pre className="gen-code">{cell}</pre>}{error&&<p role="alert" className="gen-error">{error}</p>}</DialogContent><DialogActions><Button disabled={busy} onClick={()=>setModal(null)}>{modal==='cell'?'关闭':'取消'}</Button>
 {modal==='write'&&<Button appearance="primary" disabled={busy||session.readOnly} onClick={()=>void run(async()=>{setModal(null);try{const r=await gen.write(preview!.id,session.id);setReport(r);setPreview(p=>p?{...p,status:'consumed'}:p);setStep(3);if(r.error||r.cancelled){const message=r.error??'写入已停止，请核对已提交数量';setError(message);setFailure(message);notify.error(message,'写入未全部完成');}else notify.success('写入完成',`已提交 ${r.inserted} 条`);}catch(e){try{setPreview(await gen.preview(preview!.id,preview!.offset));}catch{}throw e;}})}>写入 {preview?.count} 条</Button>}
 {modal==='save'&&<><Button disabled={busy||!templateName.trim()} onClick={()=>void run(async()=>{const t=makeTemplate(templateName.trim());await storeTemplate(t);setTemplateId(t.id);setModal(null);})}>另存为新模板</Button>{templateId&&<Button appearance="primary" disabled={busy||!templateName.trim()} onClick={()=>void run(async()=>{await storeTemplate(makeTemplate(templateName.trim(),templateId));setModal(null);})}>更新当前模板</Button>}</>}
 {modal==='delete'&&<Button appearance="primary" disabled={busy} onClick={()=>void run(async()=>{await deleteTemplate(templateId);setTemplateId('');setModal(null);})}>删除</Button>}
 {modal==='suggest'&&suggestion&&<Button appearance="primary" onClick={()=>{change({fields:suggestion.fields});setSelected([]);setModal(null);}}>应用建议，继续编辑</Button>}
 </DialogActions></DialogBody></DialogSurface></Dialog></div>;
}
function RuleDialog({field,onClose,onSave}:{field:FieldRule;onClose:()=>void;onSave:(f:FieldRule)=>void}){
 const jsonKeys=['value','values','fields'];
 const [args,setArgs]=useState(field.args),[texts,setTexts]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(field.args).map(([k,v])=>[k,typeof v==='string'&&!jsonKeys.includes(k)?v:JSON.stringify(v,null,2)]))),[error,setError]=useState('');
 const saveArgs=()=>{try{const result={...args};for(const [k,text]of Object.entries(texts)){if(jsonKeys.includes(k))result[k]=JSON.parse(text);else if(k==='scale')result[k]=Number(text);else result[k]=text;}assertSafeNumbers(result);onSave({...field,args:result});}catch(e){setError('参数无效：'+errorText(e)+'。文本值需要双引号，数组使用 [ ]');}};
 return <Dialog open onOpenChange={(_,d)=>{if(!d.open)onClose();}}><DialogSurface style={{width:'min(600px,90vw)'}}><DialogBody><DialogTitle>{field.name} · {RULES[field.kind].label}</DialogTitle><DialogContent style={{display:'flex',flexDirection:'column',gap:12,maxHeight:'60vh',overflow:'auto'}}>{Object.entries(args).map(([k])=><Field key={k} label={({value:'固定值（JSON：文本加双引号）',values:'候选值（JSON 数组）',fields:'引用字段名称（JSON 数组）',start:'起始值',end:'结束值',step:'递增步长',min:'最小值',max:'最大值',scale:'小数位数',pattern:'文本模板',prompt:'本字段的 AI 要求',op:'计算操作',separator:'连接符'} as Record<string,string>)[k]??k}>{k==='pattern'?<TemplateEditor value={texts[k]} onChange={value=>setTexts({...texts,[k]:value})}/>:k==='op'?<select className="dw-native-select" value={texts[k]} onChange={e=>setTexts({...texts,[k]:e.target.value})}>{['concat','add','multiply'].map(v=><option key={v}>{v}</option>)}</select>:jsonKeys.includes(k)?<textarea className="gen-json" value={texts[k]} onChange={e=>setTexts({...texts,[k]:e.target.value})}/>:<Input value={texts[k]} onChange={(_,d)=>setTexts({...texts,[k]:d.value})}/>}</Field>)}{RULES[field.kind].help&&<InfoHint label="规则参数说明">{RULES[field.kind].help}</InfoHint>}{error&&<p role="alert" className="gen-error">{error}</p>}<Button size="small" onClick={()=>{const a=structuredClone(RULES[field.kind].args);setArgs(a);setTexts(Object.fromEntries(Object.entries(a).map(([k,v])=>[k,typeof v==='string'&&!jsonKeys.includes(k)?v:JSON.stringify(v,null,2)])));}}>恢复规则默认参数</Button></DialogContent><DialogActions><Button onClick={onClose}>取消</Button><Button appearance="primary" onClick={saveArgs}>应用参数</Button></DialogActions></DialogBody></DialogSurface></Dialog>;
}
