import {useEffect,useRef,useState} from 'react';
import {Button,Checkbox,Input,Select,tokens} from '@fluentui/react-components';
import Editor,{DiffEditor} from '@monaco-editor/react';
import {normalizeError} from '../../ipc';
import {formatDbValue,type QueryOutcome} from '../../ipc/types';
import {useEditorTheme} from '../../useEditorTheme';
import {useSessionStore} from '../../stores/useSessionStore';
import {useTabStore} from '../../stores/useTabStore';
import {confirmEdits,usePendingEdit} from '../../stores/useEditGuard';
import {TaskActivity} from '../../app/TaskActivity';
import {mysqlApi,OBJECT_LABELS,type ObjectKind,type Catalog,type Definition,type MysqlObject} from './model';
const quote=(s:string)=>'`'+s.replace(/`/g,'``')+'`';
function template(kind:ObjectKind,name:string,table?:string){const n=quote(name);switch(kind){case 'view':return `CREATE VIEW ${n} AS\nSELECT 1 AS value`;case 'procedure':return `CREATE PROCEDURE ${n}(IN p_value INT)\nBEGIN\n  SELECT p_value AS value;\nEND`;case 'function':return `CREATE FUNCTION ${n}(p_value INT) RETURNS INT\nDETERMINISTIC NO SQL\nRETURN p_value`;case 'trigger':return `CREATE TRIGGER ${n} BEFORE INSERT ON ${quote(table||'table_name')}\nFOR EACH ROW\nBEGIN\n  SET NEW.column_name = NEW.column_name;\nEND`;case 'event':return `CREATE EVENT ${n}\nON SCHEDULE EVERY 1 DAY\nDISABLE\nDO\nBEGIN\n  SELECT 1;\nEND`;}}
export function ObjectsPanel({sessionId,database,table,tabId,onBusy}:{sessionId:string;database:string;table?:string;tabId:string;onBusy:(busy:boolean)=>void}){
 const [catalog,setCatalog]=useState<Catalog|null>(null),[kind,setKind]=useState<ObjectKind>(table?'trigger':'view'),[search,setSearch]=useState(''),[object,setObject]=useState<MysqlObject|null>(null),[definition,setDefinition]=useState<Definition|null>(null),[sql,setSql]=useState(''),[name,setName]=useState(''),[diff,setDiff]=useState(false),[deleting,setDeleting]=useState(false),[confirmed,setConfirmed]=useState(false),[callConfirmed,setCallConfirmed]=useState(false),[params,setParams]=useState<(string|null)[]>([]),[results,setResults]=useState<QueryOutcome[]>([]),[truncated,setTruncated]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const lock=useRef(false),theme=useEditorTheme();const readOnly=useSessionStore(s=>s.sessions.find(x=>x.id===sessionId)?.readOnly);const dirty=!!sql&&sql!==(definition?.sql??'');
 const refresh=async()=>setCatalog(await mysqlApi.objects(sessionId,database));
 useEffect(()=>{let live=true;void mysqlApi.objects(sessionId,database).then(v=>{if(live)setCatalog(v);}).catch(e=>{if(live)setError(normalizeError(e).message);});return()=>{live=false;};},[sessionId,database]);
 useEffect(()=>{onBusy(busy||dirty);return()=>onBusy(false);},[busy,dirty,onBusy]);
 const reset=()=>{setDefinition(null);setSql('');setObject(null);setDiff(false);setConfirmed(false);setDeleting(false);setResults([]);setNotice('');setCallConfirmed(false);};
 const operation=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await fn();}catch(e){setError(normalizeError(e).message);}finally{lock.current=false;setBusy(false);}};
 const apply=async()=>{if(!confirmed||!diff)throw Error('请先预览差异并勾选确认');await mysqlApi.apply({sessionId,database,kind:object?.kind??kind,name:object?.name??name,sql:deleting?null:sql,original:definition?.sql??null,confirmed});setNotice('操作已完成');reset();await refresh();};
 usePendingEdit({tabId,sessionId,label:'数据库对象定义',busy:()=>busy,save:apply,discard:reset},dirty||busy);
 const navigate=async(fn:()=>Promise<void>)=>{if(await confirmEdits(e=>e.tabId===tabId))await operation(fn);};
 const load=(o:MysqlObject)=>void navigate(async()=>{const d=await mysqlApi.definition(sessionId,database,o.kind,o.name);reset();setObject(o);setDefinition(d);setSql(d.sql);setParams(d.parameters.map(()=>''));});
 const filtered=(catalog?.objects??[]).filter(o=>o.kind===kind&&(!table||kind!=='trigger'||o.parent===table)&&`${o.name} ${o.parent??''} ${o.detail}`.toLowerCase().includes(search.toLowerCase()));
 return <><div style={{display:'flex',gap:6,alignItems:'center',marginBlock:8}}><Select size="small" aria-label="对象类别" value={kind} disabled={busy} onChange={(_,d)=>{if(!dirty){reset();setKind(d.value as ObjectKind);}else setError('请先保存或废弃当前修改');}}>{Object.entries(OBJECT_LABELS).map(([k,n])=><option value={k} key={k}>{n} · {catalog?.objects.filter(o=>o.kind===k).length??0}</option>)}</Select><Input size="small" placeholder="搜索对象名称 / 表 / 状态" aria-label="搜索对象" value={search} onChange={(_,d)=>setSearch(d.value)}/><Button size="small" disabled={busy} onClick={()=>void operation(refresh)}>刷新</Button><span style={{marginLeft:'auto',fontSize:11}}>{catalog?.version} · 事件调度器 {catalog?.scheduler??'—'}</span></div>
 <div style={{display:'grid',gridTemplateColumns:'minmax(180px,240px) minmax(320px,1fr)',gap:8,minHeight:420}}><aside style={{border:`1px solid ${tokens.colorNeutralStroke2}`,borderRadius:4,overflow:'auto',maxHeight:640}}>{filtered.map(o=><button key={o.name} disabled={busy} onClick={()=>load(o)} style={{display:'block',width:'100%',textAlign:'left',border:0,borderBottom:`1px solid ${tokens.colorNeutralStroke2}`,padding:'6px 8px',background:object?.name===o.name?tokens.colorNeutralBackground3:'transparent',color:tokens.colorNeutralForeground1,cursor:'pointer'}}><div style={{fontSize:12,overflowWrap:'anywhere'}}>{o.name}</div><div style={{fontSize:11,color:tokens.colorNeutralForeground3,marginTop:2}}>{o.parent?o.parent+' · ':''}{o.detail}</div></button>)}{!filtered.length&&<div style={{padding:8}}>没有可见对象；列表受服务器权限限制。</div>}</aside>
 <section style={{minWidth:0}}><div style={{display:'flex',gap:6,alignItems:'center',flexWrap:'wrap',marginBottom:6}}><Input size="small" placeholder="新对象名称" aria-label="新对象名称" value={name} maxLength={64} disabled={busy||readOnly} onChange={(_,d)=>setName(d.value)}/><Button size="small" disabled={busy||readOnly||!name.trim()} onClick={()=>void navigate(async()=>{reset();setSql(template(kind,name.trim(),table));})}>新建{OBJECT_LABELS[kind]}</Button>{object?.kind==='view'&&<Button size="small" onClick={()=>useTabStore.getState().openTable({sessionId,database,table:object.name},'data')}>预览视图数据</Button>}{definition&&<Button size="small" disabled={busy||readOnly} onClick={()=>{setDeleting(true);setDiff(true);setConfirmed(false);}}>删除对象…</Button>}</div>
 {sql?<><div style={{display:'flex',gap:6,alignItems:'center',marginBottom:6}}><span>{object?.name??name}</span><Button size="small" disabled={busy} onClick={()=>{setDiff(!diff);setDeleting(false);setConfirmed(false);}}>{diff?'返回编辑':'预览差异'}</Button><Button size="small" disabled={busy||!dirty} onClick={()=>{setSql(definition?.sql??'');setDiff(false);setConfirmed(false);}}>废弃修改</Button></div>{diff?<DiffEditor keepCurrentOriginalModel keepCurrentModifiedModel onMount={editor=>{const models=editor.getModel();editor.onDidDispose(()=>queueMicrotask(()=>{models?.original.dispose();models?.modified.dispose();}));}} height="280px" language="sql" original={definition?.sql??''} modified={deleting?'':sql} theme={theme.name} beforeMount={theme.beforeMount} options={{readOnly:true,fontSize:12,renderSideBySide:true,minimap:{enabled:false},automaticLayout:true,scrollBeyondLastLine:false}}/>:<Editor height="280px" language="sql" value={sql} onChange={v=>{setSql(v??'');setConfirmed(false);}} theme={theme.name} beforeMount={theme.beforeMount} options={{readOnly:!!readOnly||busy,fontSize:12,lineHeight:18,minimap:{enabled:false},automaticLayout:true,scrollBeyondLastLine:false}}/>}
 {diff&&!readOnly&&<div><Checkbox disabled={busy} checked={confirmed} onChange={(_,d)=>setConfirmed(!!d.checked)} label={`确认${deleting?'删除':'保存'} ${database}.${object?.name??name}；替换通过 DROP + CREATE 完成，DDL 不保证回滚，失败时须用保留的原定义恢复`}/><Button size="small" appearance="primary" disabled={busy||!confirmed} onClick={()=>void operation(apply)}>{deleting?'确认删除':'执行变更'}</Button></div>}
 {definition&&<details style={{marginBlock:8}}><summary>静态依赖与创建环境</summary><div>{definition.dependencies.join('、')||'未识别到直接依赖'}（不包含全部动态 SQL / 隐式依赖）</div><div>SQL_MODE：{definition.sqlMode||'—'} · 字符集：{definition.charset||'—'} · 排序规则：{definition.collation||'—'}</div></details>}
 {object?.kind==='procedure'&&definition&&<details><summary>调用存储过程</summary><div style={{display:'flex',gap:6,flexWrap:'wrap',marginBlock:6}}>{definition.parameters.map((p,i)=><label key={p.name} style={{display:'grid',gap:3}}><span>{p.name} · {p.mode} · {p.dataType}</span><Input size="small" disabled={busy||p.mode==='OUT'||params[i]===null||readOnly} value={params[i]??''} onChange={(_,d)=>setParams(v=>v.map((old,j)=>j===i?d.value:old))}/><Checkbox disabled={busy||p.mode==='OUT'||readOnly} checked={params[i]===null} label="NULL" onChange={(_,d)=>setParams(v=>v.map((old,j)=>j===i?(d.checked?null:''):old))}/></label>)}</div><Checkbox disabled={busy||readOnly} checked={callConfirmed} onChange={(_,d)=>setCallConfirmed(!!d.checked)} label="确认执行过程，已核对过程及其调用对象可能产生的写入和跨库影响"/><Button size="small" disabled={busy||readOnly||!callConfirmed||dirty} onClick={()=>void operation(async()=>{const r=await mysqlApi.call({sessionId,database,name:object.name,values:params,confirmed:callConfirmed},tabId);setResults(r.results);setTruncated(r.truncated);})}>调用</Button><TaskActivity kind="修改" tabId={tabId}/>{truncated&&<p>结果已截断：最多 20 组结果，每组预览 200 行；服务器结果已完整消费。</p>}{results.map((r,i)=><details open key={i}><summary>结果 {i+1} · {r.rows.length} 行 · 影响 {r.affected??0} 行</summary><div style={{maxHeight:200,overflow:'auto'}}><table style={{fontSize:12,borderCollapse:'collapse',width:'100%'}}><thead><tr>{r.columns.map((c,j)=><th key={j} style={{textAlign:'left',fontWeight:400,padding:4}}>{c.name}</th>)}</tr></thead><tbody>{r.rows.map((row,j)=><tr key={j}>{row.map((v,k)=><td key={k} style={{padding:4,borderTop:`1px solid ${tokens.colorNeutralStroke2}`,maxWidth:300,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{formatDbValue(v)}</td>)}</tr>)}</tbody></table></div></details>)}</details>}
 </>:<div style={{padding:12,color:tokens.colorNeutralForeground3}}>选择对象查看定义，或输入名称创建对象。事件默认模板为停用状态。</div>}</section></div>
 {error&&<p role="alert" style={{color:tokens.colorPaletteRedForeground1,whiteSpace:'pre-wrap'}}>{error}</p>}{notice&&<p role="status">{notice}</p>}
 </>;
}
