import {useEffect,useRef,useState} from 'react';
import {Button,Checkbox,Field,Select,tokens} from '@fluentui/react-components';
import {open} from '@tauri-apps/plugin-dialog';
import {revealItemInDir} from '@tauri-apps/plugin-opener';
import {normalizeError} from '../../ipc';
import {useSessionStore} from '../../stores/useSessionStore';
import {usePendingEdit} from '../../stores/useEditGuard';
import {TaskActivity} from '../../app/TaskActivity';
import {TransferProfiles} from '../transfer/TransferProfiles';
import {mysqlApi,type ImportPreview,type ImportReport} from './model';
export function SqlImportPanel({sessionId,database,tabId,onBusy}:{sessionId:string;database:string;tabId:string;onBusy:(busy:boolean)=>void}){
 const [path,setPath]=useState(''),[encoding,setEncoding]=useState('utf-8'),[keepGoing,setKeepGoing]=useState(false),[preview,setPreview]=useState<ImportPreview|null>(null),[report,setReport]=useState<ImportReport|null>(null),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false);
 const readOnly=useSessionStore(s=>s.sessions.find(x=>x.id===sessionId)?.readOnly);
 useEffect(()=>{onBusy(busy);return()=>onBusy(false);},[busy,onBusy]);
 usePendingEdit({tabId,sessionId,label:'SQL 文件导入',busy:()=>busy,save:async()=>{},discard:()=>{}},busy);
 const invalidate=()=>{setPreview(null);setConfirmed(false);setReport(null);};
 const run=async(execute=false)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(execute&&preview){const directory=await open({directory:true,multiple:false,title:'选择导入报告保存目录'});if(typeof directory!=='string')return;setReport(await mysqlApi.execute(sessionId,preview.id,directory,tabId));setPreview(null);setConfirmed(false);}else{setReport(null);setPreview(await mysqlApi.preview({sessionId,database,path,encoding,continueOnError:keepGoing},tabId));setConfirmed(false);}}catch(e){setError(normalizeError(e).message);}finally{lock.current=false;setBusy(false);}};
 return <section><TransferProfiles kind="import" disabled={busy} value={{encoding,continueOnError:keepGoing,sessionId,database}} onApply={v=>{invalidate();setEncoding(['utf-8','gbk','utf-16le','utf-16be','windows-1252'].includes(String(v.encoding))?String(v.encoding):'utf-8');setKeepGoing(v.continueOnError===true);if(v.sessionId!==sessionId||v.database!==database)setError(`方案原目标库为 ${String(v.database)}；当前目标为 ${database}，请重新核对。`);}}/>
 <div style={{display:'flex',gap:8,alignItems:'end',marginBlock:8}}><Button size="small" disabled={busy} onClick={()=>void open({multiple:false,filters:[{name:'SQL 文件',extensions:['sql']}]}).then(p=>{if(typeof p==='string'){setPath(p);invalidate();}}).catch(e=>setError(normalizeError(e).message))}>选择 SQL 文件</Button><span title={path} style={{flex:1,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{path||'尚未选择文件'}</span><Field label="文件编码"><Select size="small" value={encoding} disabled={busy} onChange={(_,d)=>{setEncoding(d.value);invalidate();}}>{['utf-8','gbk','utf-16le','utf-16be','windows-1252'].map(e=><option key={e}>{e}</option>)}</Select></Field><Button size="small" disabled={!path||busy||readOnly} onClick={()=>void run()}>预检文件</Button></div>
 <Checkbox size="medium" checked={keepGoing} disabled={busy} label="明确的语句错误后继续（默认遇错停止；连接中断始终停止）" onChange={(_,d)=>{setKeepGoing(!!d.checked);invalidate();}}/>
 {readOnly&&<p>只读会话不能导入 SQL 文件。</p>}<TaskActivity kind="导入" tabId={tabId}/>
 {preview&&<><div style={{display:'flex',gap:12,marginBlock:8}}><strong>{preview.statements.toLocaleString()} 条语句</strong><span>{(preview.bytes/1048576).toFixed(2)} MiB</span><span>目标：{database}</span></div><details open><summary>作用范围</summary><div style={{maxHeight:100,overflow:'auto',whiteSpace:'pre-wrap'}}>{preview.scopes.join('\n')}</div></details><details open><summary>语句预览（前 200 条，每条最多 400 字）</summary><div style={{maxHeight:250,overflow:'auto'}}>{preview.samples.map((s,i)=><div key={i} style={{display:'flex',gap:8,borderBottom:`1px solid ${tokens.colorNeutralStroke2}`,paddingBlock:4}}><span style={{minWidth:65}}>行 {s.line}</span><code style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{s.sql}</code></div>)}</div></details><div style={{fontSize:11,marginBlock:8}}>{preview.warnings.map(w=><div key={w}>{w}</div>)}</div><Checkbox checked={confirmed} disabled={busy} label={`确认向 ${database} 执行预览脚本，并已核对库切换、删除及存储程序的间接影响`} onChange={(_,d)=>setConfirmed(!!d.checked)}/><Button size="small" appearance="primary" disabled={busy||!confirmed||readOnly} onClick={()=>void run(true)}>选择报告目录并执行</Button></>}
 {error&&<p role="alert" style={{color:tokens.colorPaletteRedForeground1,whiteSpace:'pre-wrap'}}>{error}</p>}
 {report&&<><p role="status">执行成功 {report.executed} 条 · 明确失败 {report.failed} 条{report.cancelled?' · 已取消':''}{report.uncertain?' · 存在待核对语句':''}</p>{report.error&&<p role="alert">{report.error}</p>}<p>{report.uncertain?'连接状态不确定，请核对服务器中的事务和写入结果。':'未提交事务已在结束时回滚；此前已提交的修改保留。'}完整逐语句报告不保存 SQL 内容。</p><Button size="small" onClick={()=>void revealItemInDir(report.reportPath).catch(e=>setError(normalizeError(e).message))}>打开执行报告位置</Button><div style={{maxHeight:250,overflow:'auto',marginTop:6}}>{report.entries.map(e=><div key={e.number} style={{padding:3,borderBottom:`1px solid ${tokens.colorNeutralStroke2}`}}>#{e.number} · 行 {e.line} · {e.database} · {e.status==='success'?'成功':e.status==='failed'?'失败':'待核对'} · 影响 {e.affected} 行 {e.error}</div>)}</div></>}
 </section>;
}
