import {InfoHint} from '../../common/InfoHint';
import {useEffect,useRef,useState} from 'react';
import {Button,Checkbox,Dialog,DialogSurface,DialogBody,DialogTitle,DialogContent,DialogActions,Field,Input,Spinner} from '@fluentui/react-components';
import {AddRegular,SaveRegular,DeleteRegular,ArrowSyncRegular,PlugConnectedRegular} from '@fluentui/react-icons';
import {generationApi, type Provider} from '../generation/model';
import {errorText} from '../../stores/useTaskStore';
import '../generation/generation.css';
const fresh=():Provider=>({id:crypto.randomUUID(),name:'新 AI 服务',baseUrl:'https://api.openai.com/v1',model:'',outputFormat:'json',tokenParameter:'max_tokens',timeoutSeconds:60,maxTokens:4096,isDefault:false,hasKey:false});
export function AiSettings(){
 const [providers,setProviders]=useState<Provider[]>([]),[draft,setDraft]=useState<Provider|null>(null),[key,setKey]=useState<string|null>(null),[models,setModels]=useState<string[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[removing,setRemoving]=useState(false),[dirty,setDirty]=useState(false);
 const lock=useRef(false);
 const run=async(f:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');setMessage('');try{await f();}catch(e){setError(errorText(e));}finally{lock.current=false;setBusy(false);}};
 useEffect(()=>{void run(async()=>{const list=await generationApi.providers();setProviders(list);setDraft(list.find(p=>p.isDefault)??list[0]??fresh());});},[]);
 const patch=(v:Partial<Provider>)=>{setDraft(d=>d?{...d,...v}:d);setDirty(true);};
 const select=(p:Provider)=>{setDraft({...p});setKey(null);setModels([]);setDirty(false);setError('');setMessage('');};
 return <div className="dw-generation dw-ai-settings"><h2>AI 服务</h2><InfoHint label="AI 服务配置说明">兼容 OpenAI Chat Completions 接口。先填写基础地址和密钥，获取模型列表后选择模型；接口未提供模型列表时可手动输入。密钥仅保存在 Windows 凭据管理器。</InfoHint>
 <div className="gen-toolbar"><label>已保存服务 <select className="dw-native-select" disabled={busy||dirty} value={providers.some(p=>p.id===draft?.id)?draft?.id:''} onChange={e=>{const p=providers.find(p=>p.id===e.target.value);if(p)select(p);}}><option value="" disabled>新服务</option>{providers.map(p=><option key={p.id} value={p.id}>{p.name}{p.isDefault?' · 默认':''}</option>)}</select></label><Button icon={<AddRegular/>} disabled={busy||dirty||providers.length>=20} onClick={()=>select(fresh())}>新增服务</Button>{dirty&&<Button disabled={busy} onClick={()=>select(providers.find(p=>p.id===draft?.id)??fresh())}>撤销未保存修改</Button>}</div>
 {draft&&<fieldset disabled={busy} className="gen-form"><div className="gen-two"><Field label="服务名称"><Input value={draft.name} onChange={(_,d)=>patch({name:d.value})}/></Field><Field label="API Base URL"><Input value={draft.baseUrl} placeholder="https://example.com/v1" onChange={(_,d)=>{patch({baseUrl:d.value});setModels([]);}}/></Field><Field label="API Key（本地无密钥服务可留空）"><Input type="password" autoComplete="new-password" value={key??''} placeholder={draft.hasKey?'已保存，留空保持原密钥':'输入服务密钥'} onChange={(_,d)=>{setKey(d.value||null);setDirty(true);}}/></Field><Field label="模型 ID"><Input value={draft.model} placeholder="填写或从下方模型列表选择" onChange={(_,d)=>patch({model:d.value})}/></Field></div>
 <div className="gen-toolbar"><Button icon={<ArrowSyncRegular/>} onClick={()=>void run(async()=>{const list=await generationApi.models(draft,key);setModels(list);setMessage(list.length?`获取到 ${list.length} 个模型`:'服务返回空列表，请手动填写模型 ID');})}>获取模型列表</Button><Button icon={<PlugConnectedRegular/>} disabled={!draft.model} onClick={()=>void run(async()=>{const r=await generationApi.test(draft,key);setMessage(`模型测试通过 · 输入 ${r.usage.inputTokens??'未报告'} / 输出 ${r.usage.outputTokens??'未报告'} tokens`);})}>测试连接与输出</Button><span className="gen-note">测试可能计费</span>{draft.hasKey&&<Button onClick={()=>{setKey('');setDirty(true);setMessage('保存后移除密钥');}}>移除保存的密钥</Button>}</div>
 {!!models.length&&<Field label="选择已获取的模型"><select className="dw-native-select" size={Math.min(7,models.length)} value={draft.model} onChange={e=>patch({model:e.target.value})}>{models.map(m=><option key={m} value={m}>{m}</option>)}</select></Field>}
 <div className="gen-two"><Field label="输出格式"><select className="dw-native-select" value={draft.outputFormat} onChange={e=>patch({outputFormat:e.target.value as Provider['outputFormat']})}><option value="json">JSON 模式</option><option value="schema">JSON Schema（支持时）</option><option value="text">普通文本（兼容性优先）</option></select></Field><Field label="输出上限参数"><select className="dw-native-select" value={draft.tokenParameter} onChange={e=>patch({tokenParameter:e.target.value as Provider['tokenParameter']})}><option value="max_tokens">max_tokens（通用兼容）</option><option value="max_completion_tokens">max_completion_tokens</option></select></Field><Field label="超时（5–300 秒）"><Input type="number" min={5} max={300} value={String(draft.timeoutSeconds)} onChange={(_,d)=>patch({timeoutSeconds:Number(d.value)})}/></Field><Field label="输出 token 上限（128–32768）"><Input type="number" min={128} max={32768} value={String(draft.maxTokens)} onChange={(_,d)=>patch({maxTokens:Number(d.value)})}/></Field></div>
 <Checkbox checked={draft.isDefault} label="设为默认服务" onChange={(_,d)=>patch({isDefault:!!d.checked})}/><InfoHint label="模型兼容性说明">模型列表不保证输出格式兼容。规则建议在 Schema 模式下仍使用 JSON 模式并做本地校验。</InfoHint>
 <div className="gen-toolbar"><Button appearance="primary" icon={<SaveRegular/>} disabled={!draft.name.trim()||!draft.baseUrl.trim()||!draft.model.trim()} onClick={()=>void run(async()=>{const list=await generationApi.saveProvider(draft,key);setProviders(list);select(list.find(p=>p.id===draft.id)!);setMessage('AI 服务已保存');})}>保存服务</Button><Button icon={<DeleteRegular/>} disabled={!providers.some(p=>p.id===draft.id)} onClick={()=>setRemoving(true)}>删除服务</Button>{dirty&&<span className="gen-note">有未保存的设置</span>}</div></fieldset>}
 {busy&&<Spinner size="tiny" label="处理中，可在任务中心取消网络请求"/>}{message&&<p role="status">{message}</p>}{error&&<p role="alert" className="gen-error">{error}</p>}
 <Dialog open={removing} onOpenChange={(_,d)=>{if(!busy)setRemoving(d.open);}}><DialogSurface><DialogBody><DialogTitle>删除 AI 服务？</DialogTitle><DialogContent>删除「{draft?.name}」及其保存的密钥。已有模板保留，不包含密钥。</DialogContent><DialogActions><Button disabled={busy} onClick={()=>setRemoving(false)}>取消</Button><Button appearance="primary" disabled={busy} onClick={()=>void run(async()=>{const list=await generationApi.removeProvider(draft!.id);setProviders(list);select(list[0]??fresh());setRemoving(false);})}>删除</Button></DialogActions></DialogBody></DialogSurface></Dialog></div>;
}
