const fs=require('node:fs'),ts=require('typescript'),assert=require('node:assert/strict');
const data=new Map(),writes=[];
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
let system=()=>Promise.resolve('#0f6cbd'),persist=async(key,value)=>{data.set(key,value);};
const api={settingsGet:async key=>data.get(key)??null,settingsSet:(key,value)=>{if(key==='ui_accent')writes.push(value);return persist(key,value);},systemAccentColor:()=>system()};
const m={exports:{}};
new Function('require','module','exports',ts.transpileModule(fs.readFileSync('src/stores/useSettingsStore.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText)(name=>name==='../ipc'?{api}:require(name),m,m.exports);
const store=m.exports.useSettingsStore;
const tick=()=>new Promise(resolve=>setImmediate(resolve));
(async()=>{
 await store.getState().load();
 const lookup=deferred();system=()=>lookup.promise;
 const old=store.getState().setAccent('system');
 await store.getState().setAccent('#123456');lookup.resolve('#abcdef');await old;
 assert.equal(store.getState().resolvedAccent,'#123456');assert.deepEqual(writes,['#123456'],'迟到的系统色不覆盖新选择');
 const gate=deferred();persist=async(key,value)=>{if(value==='#112233')await gate.promise;data.set(key,value);};
 const first=store.getState().setAccent('#112233');await tick();
 const second=store.getState().setAccent('#445566');await tick();
 assert.equal(writes.at(-1),'#112233','前一次写入结束之前不并发写盘');
 gate.resolve();await Promise.all([first,second]);
 assert.equal(data.get('ui_accent'),'#445566');assert.equal(store.getState().resolvedAccent,'#445566');
 persist=async()=>{throw Error('模拟写盘失败');};
 await assert.rejects(store.getState().setAccent('#778899'));assert.equal(store.getState().resolvedAccent,'#445566');
 persist=async(key,value)=>data.set(key,value);
 await store.getState().setAccent('#778899');assert.equal(store.getState().resolvedAccent,'#778899');
 await store.getState().load();assert.equal(store.getState().accent,'#778899');
 const gate2=deferred();persist=async(key,value)=>{if(value==='#010203')await gate2.promise;if(value==='#040506')throw Error('后续写入失败');data.set(key,value);};
 const committed=store.getState().setAccent('#010203');await tick();
 const rejected=assert.rejects(store.getState().setAccent('#040506'));await tick();gate2.resolve();
 await Promise.all([committed,rejected]);
 assert.equal(store.getState().resolvedAccent,data.get('ui_accent'),'后续失败时界面仍匹配最后成功写入的配色');
 console.log('通过：强调色串行写入、最后选择优先、迟到系统色隔离、失败保留与重试、重启恢复。');
})().catch(e=>{console.error(e);process.exitCode=1;});
