import type { Engine, TableMeta } from "../../ipc/types";
import { quoteIdent } from "../grid/value";

/**
 * 由统一元数据重建可读 DDL（PostgreSQL 没有 SHOW CREATE TABLE 等价物，
 * 其他引擎在缺少原始 DDL 时也可作为回退）。
 */
export function generateDdl(engine: Engine, detail: TableMeta): string {
  const q = (name: string) => quoteIdent(engine, name);
  const schemaPrefix =
    engine === "postgres" && detail.schema ? `${q(detail.schema)}.` : "";
  const tableRef = `${schemaPrefix}${q(detail.name)}`;
  const pkSet = new Set(detail.primaryKey);
  const sqliteSinglePk = engine === "sqlite" && detail.primaryKey.length === 1;

  const parts: string[] = [];
  for (const column of detail.columns) {
    const isSqliteInlinePk = sqliteSinglePk && pkSet.has(column.name);
    let def = `${q(column.name)} ${column.rawType || "TEXT"}`;
    if (isSqliteInlinePk) {
      def += " PRIMARY KEY";
      if (column.autoIncrement) def += " AUTOINCREMENT";
    }
    if (!column.nullable && !isSqliteInlinePk) def += " NOT NULL";

    const defaultValue = column.defaultValue?.trim();
    const hasNextval = defaultValue?.toLowerCase().includes("nextval(") ?? false;
    if (defaultValue && !column.autoIncrement && defaultValue !== "NULL") {
      def += ` DEFAULT ${defaultValue}`;
    } else if (defaultValue && column.autoIncrement && hasNextval) {
      def += ` DEFAULT ${defaultValue}`;
    }
    if (engine === "mysql" && column.autoIncrement) def += " AUTO_INCREMENT";
    if (engine === "postgres" && column.autoIncrement && !hasNextval) {
      def += " GENERATED BY DEFAULT AS IDENTITY";
    }
    parts.push(def);
  }

  if (!sqliteSinglePk && detail.primaryKey.length > 0) {
    parts.push(`PRIMARY KEY (${detail.primaryKey.map(q).join(", ")})`);
  }

  for (const fk of detail.foreignKeys) {
    const columns = fk.columns.map(q).join(", ");
    const refColumns = fk.refColumns.map(q).join(", ");
    let clause = `CONSTRAINT ${q(fk.name)} FOREIGN KEY (${columns}) REFERENCES ${
      schemaPrefix && !fk.refTable.includes(".")
        ? `${schemaPrefix}${q(fk.refTable)}`
        : q(fk.refTable)
    } (${refColumns})`;
    if (fk.onDelete && fk.onDelete.toUpperCase() !== "NO ACTION") {
      clause += ` ON DELETE ${fk.onDelete.toUpperCase()}`;
    }
    if (fk.onUpdate && fk.onUpdate.toUpperCase() !== "NO ACTION") {
      clause += ` ON UPDATE ${fk.onUpdate.toUpperCase()}`;
    }
    parts.push(clause);
  }

  const lines = [`CREATE TABLE ${tableRef} (`, ...parts.map((p) => `  ${p},`)];
  lines[lines.length - 1] = lines[lines.length - 1].replace(/,$/, "");
  lines.push(");");

  const extras: string[] = [];
  for (const index of detail.indexes) {
    if (index.primary) continue;
    const columns = index.columns
      .map((c) => `${q(c.name)}${c.desc ? " DESC" : ""}`)
      .join(", ");
    extras.push(
      `CREATE ${index.unique ? "UNIQUE " : ""}INDEX ${q(index.name)} ON ${tableRef} (${columns});`,
    );
  }

  if (engine === "postgres") {
    if (detail.comment) {
      extras.push(
        `COMMENT ON TABLE ${tableRef} IS '${detail.comment.replace(/'/g, "''")}';`,
      );
    }
    for (const column of detail.columns) {
      if (column.comment) {
        extras.push(
          `COMMENT ON COLUMN ${tableRef}.${q(column.name)} IS '${column.comment.replace(
            /'/g,
            "''",
          )}';`,
        );
      }
    }
  }

  return extras.length > 0 ? `${lines.join("\n")}\n\n${extras.join("\n")}` : lines.join("\n");
}
