import type {TablePropertyForm} from './createTableDraft';
import type {Dispatch,SetStateAction} from 'react';
import {useEffect,useState} from 'react';
import {Button,Field,Input,Select,Textarea} from '@fluentui/react-components';
import './table-options.css';
import {api,normalizeError} from '../../ipc';import type {CharsetMeta,DdlSpec,TableInfo} from '../../ipc/types';
import {useSessionStore} from '../../stores/useSessionStore';import {useTabStore,type TableTab} from '../../stores/useTabStore';
import {useEditGuard,usePendingEdit} from '../../stores/useEditGuard';import {ConfirmSqlDialog} from './ConfirmSqlDialog';
export function TableOptionsEditor({tab,info,onSaved,draft}:{tab:TableTab;info:TableInfo;onSaved:()=>void;draft?:{disabled?:boolean;value:TablePropertyForm;setValue:Dispatch<SetStateAction<TablePropertyForm>>}}){
 const session=useSessionStore(s=>s.sessions.find(v=>v.id===tab.sessionId));const mysql=session?.engine==='mysql';const readonly=!session||session.readOnly||!!draft?.disabled;
 const initial={name:info.name,comment:info.comment??'',engine:info.extra.engine??'',charset:info.extra.charset??'',collation:info.extra.collation??'',autoIncrement:info.extra.autoIncrementValue==null?'':String(info.extra.autoIncrementValue),rowFormat:''};
 const [savedForm,setSavedForm]=useState(initial),[preview,setPreview]=useState(false),[busy,setBusy]=useState(false);
 const form=draft?.value??savedForm,setForm=draft?.setValue??setSavedForm;
 const [engines,setEngines]=useState<string[]>([]),[charsets,setCharsets]=useState<CharsetMeta[]>([]),[collations,setCollations]=useState<string[]>([]),[metaError,setMetaError]=useState(''),[collationError,setCollationError]=useState(''),[collationBusy,setCollationBusy]=useState(false);
 useEffect(()=>{if(!mysql)return;let alive=true;void Promise.all([api.storageEngines(tab.sessionId),api.charsets(tab.sessionId)]).then(([e,c])=>{if(alive){setEngines(e);setCharsets(c);setMetaError('');}}).catch(e=>{if(alive)setMetaError(normalizeError(e).message);});return()=>{alive=false;};},[mysql,tab.sessionId]);
 useEffect(()=>{if(!mysql||!form.charset){setCollations([]);setCollationBusy(false);setCollationError('');return;}let alive=true;setCollations([]);setCollationBusy(true);setCollationError('');void api.collations(tab.sessionId,form.charset).then(c=>{if(alive)setCollations(c);}).catch(e=>{if(alive)setCollationError(normalizeError(e).message);}).finally(()=>{if(alive)setCollationBusy(false);});return()=>{alive=false;};},[mysql,tab.sessionId,form.charset]);
 const choose=(key:'engine'|'charset'|'collation',label:string,values:string[])=><Field size="small" label={label}><Select size="small" aria-label={label} value={form[key]} disabled={readonly||busy||(key==='collation'&&collationBusy)} onChange={(_,d)=>{setForm(v=>key==='charset'?{...v,charset:d.value,collation:charsets.find(c=>c.charset===d.value)?.defaultCollation??''}:{...v,[key]:d.value});}}>{[...new Set([form[key],...values])].filter(Boolean).map(v=><option key={v} value={v}>{v}</option>)}{(!form[key]||draft)&&<option value="">使用数据库默认值</option>}</Select></Field>;
 const changed=Object.keys(form).filter(k=>form[k as keyof typeof form]!==initial[k as keyof typeof form]);const dirty=changed.length>0;
 const options=Object.fromEntries(changed.filter(k=>k!=="collation"||!!form.collation).map(k=>[k,form[k as keyof typeof form]]));
 const spec:DdlSpec={type:'tableOptions',schema:tab.schema,table:tab.table,options};
 const reset=()=>setForm(initial);
 const apply=async()=>{if(readonly)throw Error('当前会话为只读模式');if(Object.values(useEditGuard.getState().entries).some(e=>e.tabId===tab.id&&e.label!=='表属性'))throw Error('请先保存或放弃该表的其他未保存修改');setBusy(true);try{await api.ddlApply(tab.sessionId,tab.database,spec,true);if(options.name){useTabStore.setState(s=>({tabs:s.tabs.map(t=>t.kind==='table'&&t.sessionId===tab.sessionId&&t.database===tab.database&&t.schema===tab.schema&&t.table===tab.table?{...t,table:options.name,title:options.name}:t)}));}setForm({...form,rowFormat:''});if(!options.name)onSaved();}finally{setBusy(false);}};
 usePendingEdit({tabId:tab.id,sessionId:tab.sessionId,label:'表属性',save:apply,discard:reset,preview:()=>api.ddlPreview(tab.sessionId,tab.database,spec),busy:()=>busy},dirty&&!draft,tab.id+':properties');
 const input=(key:keyof typeof form,label:string,placeholder?:string)=><Field size="small" label={label}><Input size="small" aria-label={label} value={form[key]} placeholder={placeholder} disabled={readonly||busy} onChange={(_,d)=>setForm(v=>({...v,[key]:d.value}))}/></Field>;
 return <section className="dw-table-options" aria-label="表属性设置">
 <div className="dw-table-options-basic">{input('name','表名')}{session?.engine!=='sqlite'&&<Field size="small" className="dw-table-options-comment" label="注释"><Textarea rows={1} resize="vertical" aria-label="表注释" value={form.comment} disabled={readonly||busy} onChange={(_,d)=>setForm(v=>({...v,comment:d.value}))}/></Field>}</div>
 {mysql&&<div className="dw-table-options-grid">{choose('engine','引擎',engines)}{choose('charset','默认字符集',charsets.map(c=>c.charset))}{choose('collation','默认排序规则',collations)}{(draft||info.autoIncrementColumn)&&input('autoIncrement','自增起始值')}<Field size="small" label="记录行格式"><Select size="small" aria-label="记录行格式" value={form.rowFormat} disabled={readonly||busy} onChange={(_,d)=>setForm(v=>({...v,rowFormat:d.value}))}><option value="">{draft?'数据库默认值':'保持当前格式'}</option>{['DEFAULT','DYNAMIC','COMPACT','REDUNDANT','COMPRESSED','FIXED'].map(v=><option key={v}>{v}</option>)}</Select></Field></div>}
 {(metaError||collationError)&&<div role="alert">无法加载选项：{metaError||collationError}</div>}
 {!draft&&<div className="dw-table-options-actions"><Button size="small" appearance="primary" disabled={readonly||busy||!dirty||collationBusy} onClick={()=>setPreview(true)}>预览修改</Button><Button size="small" disabled={busy||!dirty} onClick={reset}>放弃修改</Button></div>}
 <ConfirmSqlDialog open={preview} title="修改表属性" sessionId={tab.sessionId} tabId={tab.id} warning="修改引擎或记录行格式可能重建表并持有锁；默认字符集不转换已有列。改表名请单独保存。" loadPreview={()=>api.ddlPreview(tab.sessionId,tab.database,spec)} onApply={apply} onClose={()=>setPreview(false)} onDone={()=>setPreview(false)}/></section>;
}
