const INFO_SECTION_LABELS: Record<string, string> = {
  Server: "服务器",
  Clients: "客户端",
  Memory: "内存",
  Persistence: "持久化",
  Stats: "统计",
  Replication: "复制",
  CPU: "处理器",
  Cluster: "集群",
  Keyspace: "键空间",
  Errorstats: "错误统计",
  Commandstats: "命令统计",
  Latencystats: "延迟统计",
};

const INFO_KEY_LABELS: Record<string, string> = {
  redis_version: "Redis 版本",
  redis_git_sha1: "Git SHA1",
  redis_git_dirty: "Git 有未提交改动",
  redis_build_id: "构建 ID",
  redis_mode: "运行模式",
  os: "操作系统",
  arch_bits: "架构位数",
  monotonic_clock: "单调时钟源",
  multiplexing_api: "多路复用 API",
  atomicvar_api: "原子变量 API",
  gcc_version: "GCC 版本",
  process_id: "进程 ID",
  process_supervised: "进程托管",
  run_id: "运行 ID",
  tcp_port: "TCP 端口",
  server_time_usec: "服务器时间（微秒）",
  uptime_in_seconds: "运行秒数",
  uptime_in_days: "运行天数",
  hz: "定时频率",
  configured_hz: "配置定时频率",
  lru_clock: "LRU 时钟",
  executable: "可执行文件",
  config_file: "配置文件",
  io_threads_active: "活跃 IO 线程",
  io_threads: "配置 IO 线程",

  connected_clients: "已连接客户端",
  cluster_connections: "集群连接数",
  maxclients: "最大客户端数",
  client_recent_max_input_buffer: "客户端最大输入缓冲",
  client_recent_max_output_buffer: "客户端最大输出缓冲",
  blocked_clients: "阻塞客户端",
  tracking_clients: "追踪客户端",
  pubsub_clients: "发布订阅客户端",
  watching_clients: "监视客户端",
  clients_in_timeout_table: "超时表客户端",
  total_watched_keys: "被监视键总数",
  total_blocking_keys: "阻塞键总数",
  total_blocking_keys_on_nokey: "无键阻塞总数",

  used_memory: "已用内存（字节）",
  used_memory_human: "已用内存",
  used_memory_rss: "常驻内存 RSS",
  used_memory_rss_human: "常驻内存",
  used_memory_peak: "峰值内存",
  used_memory_peak_human: "峰值内存（可读）",
  used_memory_peak_perc: "峰值占比",
  used_memory_overhead: "内存开销",
  used_memory_startup: "启动内存",
  used_memory_dataset: "数据集内存",
  used_memory_dataset_perc: "数据集占比",
  allocator_allocated: "分配器已分配",
  allocator_active: "分配器活跃",
  allocator_resident: "分配器常驻",
  allocator_muzzy: "分配器 Muzzy",
  total_system_memory: "系统总内存（字节）",
  total_system_memory_human: "系统总内存",
  used_memory_lua: "Lua 内存（字节）",
  used_memory_lua_human: "Lua 内存",
  used_memory_vm_eval: "脚本 VM 内存",
  used_memory_scripts: "脚本内存",
  used_memory_scripts_human: "脚本内存（可读）",
  number_of_cached_scripts: "缓存脚本数",
  maxmemory: "最大内存限制",
  maxmemory_human: "最大内存限制（可读）",
  maxmemory_policy: "内存淘汰策略",
  allocator_frag_ratio: "分配器碎片率",
  allocator_frag_bytes: "分配器碎片字节",
  allocator_rss_ratio: "分配器 RSS 比",
  allocator_rss_bytes: "分配器 RSS 字节",
  rss_overhead_ratio: "RSS 开销比",
  rss_overhead_bytes: "RSS 开销字节",
  mem_fragmentation_ratio: "内存碎片率",
  mem_fragmentation_bytes: "内存碎片字节",
  mem_not_counted_for_evict: "不参与淘汰内存",
  mem_replication_backlog: "复制积压缓冲",
  mem_total_replication_buffers: "复制缓冲总量",
  mem_clients_slaves: "从库客户端内存",
  mem_clients_normal: "普通客户端内存",
  mem_cluster_links: "集群链路内存",
  mem_aof_buffer: "AOF 缓冲内存",
  mem_allocator: "内存分配器",
  mem_overhead_db_hashtable_lut: "哈希表查找开销",
  mem_overhead_db_hashtable_rehashing: "哈希表重哈希开销",
  active_defrag_running: "活跃碎片整理中",
  lazyfree_pending_objects: "惰性释放待处理",
  lazyfreed_objects: "已惰性释放对象",

  loading: "正在加载数据",
  async_loading: "异步加载中",
  current_cow_peak: "fork COW 峰值",
  current_cow_size: "fork COW 大小",
  current_cow_size_age: "COW 大小统计时长",
  current_fork_perc: "当前 fork 进度",
  current_save_keys_processed: "已处理保存键",
  current_save_keys_total: "保存键总数",
  rdb_changes_since_last_save: "自上次保存以来变更",
  rdb_bgsave_in_progress: "RDB 后台保存中",
  rdb_last_save_time: "上次保存时间戳",
  rdb_last_bgsave_status: "上次 RDB 保存状态",
  rdb_last_bgsave_time_sec: "上次 RDB 耗时（秒）",
  rdb_current_bgsave_time_sec: "当前 RDB 耗时（秒）",
  rdb_saves: "RDB 保存次数",
  rdb_last_cow_size: "上次 RDB COW 大小",
  rdb_last_load_keys_expired: "上次加载过期键",
  rdb_last_load_keys_loaded: "上次加载键数",
  aof_enabled: "AOF 已启用",
  aof_rewrite_in_progress: "AOF 重写中",
  aof_rewrite_scheduled: "AOF 重写已计划",
  aof_last_rewrite_time_sec: "上次 AOF 重写耗时（秒）",
  aof_current_rewrite_time_sec: "当前 AOF 重写耗时（秒）",
  aof_last_bgrewrite_status: "上次 AOF 重写状态",
  aof_rewrites: "AOF 重写次数",
  aof_rewrites_consecutive_failures: "AOF 连续重写失败",
  aof_last_write_status: "上次 AOF 写入状态",
  aof_last_cow_size: "上次 AOF COW 大小",
  module_fork_in_progress: "模块 fork 中",
  module_fork_last_cow_size: "模块 fork COW 大小",
  aof_current_size: "AOF 当前大小",
  aof_base_size: "AOF 基础大小",
  aof_pending_rewrite: "AOF 待重写",
  aof_buffer_length: "AOF 缓冲长度",
  aof_pending_bio_fsync: "AOF 待 fsync",
  aof_delayed_fsync: "AOF 延迟 fsync",

  total_connections_received: "已接收连接总数",
  total_commands_processed: "已处理命令总数",
  instantaneous_ops_per_sec: "瞬时每秒操作数",
  total_net_input_bytes: "网络输入总字节",
  total_net_output_bytes: "网络输出总字节",
  total_net_repl_input_bytes: "复制输入字节",
  total_net_repl_output_bytes: "复制输出字节",
  instantaneous_input_kbps: "瞬时输入 KB/s",
  instantaneous_output_kbps: "瞬时输出 KB/s",
  instantaneous_input_repl_kbps: "复制瞬时输入 KB/s",
  instantaneous_output_repl_kbps: "复制瞬时输出 KB/s",
  rejected_connections: "被拒绝连接数",
  sync_full: "全量同步次数",
  sync_partial_ok: "部分同步成功",
  sync_partial_err: "部分同步失败",
  expired_keys: "已过期键数",
  expired_subkeys: "已过期子键数",
  expired_stale_perc: "过期未清理比例",
  expired_time_cap_reached_count: "过期时间上限触发数",
  expire_cycle_cpu_milliseconds: "过期循环 CPU 毫秒",
  evicted_keys: "被淘汰键数",
  evicted_clients: "被淘汰客户端",
  evicted_scripts: "被淘汰脚本",
  total_eviction_exceeded_time: "淘汰超时总时长",
  current_eviction_exceeded_time: "当前淘汰超时",
  keyspace_hits: "键命中次数",
  keyspace_misses: "键未命中次数",
  pubsub_channels: "发布订阅频道数",
  pubsub_patterns: "发布订阅模式数",
  pubsubshard_channels: "分片频道数",
  latest_fork_usec: "最近 fork 微秒",
  total_forks: "fork 总次数",
  migrate_cached_sockets: "迁移缓存套接字",
  slave_expires_tracked_keys: "从库过期跟踪键",
  active_defrag_hits: "碎片整理命中",
  active_defrag_misses: "碎片整理未命中",
  active_defrag_key_hits: "碎片整理键命中",
  active_defrag_key_misses: "碎片整理键未命中",
  total_active_defrag_time: "碎片整理总时长",
  current_active_defrag_time: "当前碎片整理时长",
  tracking_total_keys: "追踪键总数",
  tracking_total_items: "追踪项总数",
  tracking_total_prefixes: "追踪前缀总数",
  unexpected_error_replies: "意外错误回复",
  total_error_replies: "错误回复总数",
  dump_payload_sanitizations: "dump 载荷净化",
  total_reads_processed: "读事件总数",
  total_writes_processed: "写事件总数",
  io_threaded_reads_processed: "IO 线程读事件",
  io_threaded_writes_processed: "IO 线程写事件",
  client_query_buffer_limit_disconnections: "查询缓冲超限断开",
  client_output_buffer_limit_disconnections: "输出缓冲超限断开",
  reply_buffer_shrinks: "回复缓冲收缩",
  reply_buffer_expands: "回复缓冲扩展",
  eventloop_cycles: "事件循环次数",
  eventloop_duration_sum: "事件循环总耗时（µs）",
  eventloop_duration_cmd_sum: "命令耗时总和（µs）",
  instantaneous_eventloop_cycles_per_sec: "瞬时事件循环/秒",
  instantaneous_eventloop_duration_usec: "瞬时事件循环耗时（µs）",

  role: "角色",
  connected_slaves: "已连接从库",
  connected_replicas: "已连接副本",
  master_failover_state: "主库故障转移状态",
  master_replid: "主库复制 ID",
  master_replid2: "主库复制 ID2",
  master_repl_offset: "主库复制偏移",
  second_repl_offset: "第二复制偏移",
  repl_backlog_active: "复制积压激活",
  repl_backlog_size: "复制积压大小",
  repl_backlog_first_byte_offset: "积压首字节偏移",
  repl_backlog_histlen: "积压历史长度",
  master_host: "主库地址",
  master_port: "主库端口",
  master_link_status: "主库链路状态",
  master_last_io_seconds_ago: "距上次主库 IO（秒）",
  master_sync_in_progress: "主库同步中",
  slave_read_repl_offset: "从库读复制偏移",
  slave_repl_offset: "从库复制偏移",
  slave_priority: "从库优先级",
  slave_read_only: "从库只读",
  replica_announced: "已公告副本",

  used_cpu_sys: "系统 CPU 耗时",
  used_cpu_user: "用户 CPU 耗时",
  used_cpu_sys_children: "子进程系统 CPU",
  used_cpu_user_children: "子进程用户 CPU",
  used_cpu_sys_main_thread: "主线程系统 CPU",
  used_cpu_user_main_thread: "主线程用户 CPU",

  cluster_enabled: "集群已启用",
  latency_tracking: "延迟追踪",
  latency_percentilep50: "延迟 P50（µs）",
  latency_percentilep99: "延迟 P99（µs）",
  latency_percentilep999: "延迟 P99.9（µs）",
};

export function sectionLabel(section: string): { label: string; original: string | null } {
  const label = INFO_SECTION_LABELS[section];
  return label ? { label, original: section } : { label: section, original: null };
}

export function keyLabel(key: string): { label: string; original: string | null } {
  const exact = INFO_KEY_LABELS[key];
  if (exact) return { label: exact, original: key };
  if (/^db\d+$/.test(key)) return { label: `数据库 ${key.slice(2)}`, original: key };
  if (key.startsWith("cmdstat_")) return { label: `命令 ${key.slice(8)}`, original: key };
  if (key.startsWith("errorstat_")) return { label: `错误 ${key.slice(10)}`, original: key };
  if (key.startsWith("latency_percentile")) {
    return { label: `延迟 ${key.slice("latency_percentile".length).toUpperCase()}（µs）`, original: key };
  }
  if (/^listener\d+$/.test(key)) {
    return { label: `监听地址 ${key.slice("listener".length)}`, original: key };
  }
  return { label: key, original: null };
}
